apiVersion: batch/v1
kind: CronJob
metadata:
  name: get-offence-actuarial-mapping
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: curl
              image: alpine/curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl -v -f -X POST http://hmpps-arns-risk-actuarial-api/admin/update-offence-mapping
          restartPolicy: Never
  concurrencyPolicy: Forbid