package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.lds.HasQualifications
import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.service.transformation.RelationshipDomainScore
import java.time.LocalDate

data class ActuarialRequest(
  val version: RiskScoreVersion = RiskScoreVersion.getLatestVersion(),
  val gender: String? = null,
  val assessmentDate: LocalDate = LocalDate.now(),
  val dateOfBirth: LocalDate? = null,
  val dateOfCurrentConviction: LocalDate? = null,
  val totalNumberOfSanctionsForAllOffences: Int? = null,
  val ageAtFirstSanction: Int? = null,
  val currentOffenceCode: String? = null,
  val dateAtStartOfFollowupUserInput: LocalDate? = null,
  val dateAtStartOfFollowupCalculated: LocalDate? = null,
  val totalNumberOfViolentSanctions: Int? = null,
  val didOffenceInvolveCarryingOrUsingWeapon: Boolean? = null,
  val suitabilityOfAccommodation: ProblemLevel? = null,
  val isUnemployed: Boolean? = null,
  val currentRelationshipWithPartner: ProblemLevel? = null,
  val hasEvidenceOfDomesticAbuse: Boolean? = null,
  val currentRelationshipStatus: CurrentRelationshipStatus?= null,
  val motivationToTackleDrugMisuse: MotivationLevel ?= null,
  val currentAlcoholUseProblems: ProblemLevel? = null,
  val excessiveAlcoholUse: ProblemLevel? = null,
  val impulsivityProblems: ProblemLevel? = null,
  val temperControl: ProblemLevel? = null,
  val proCriminalAttitudes: ProblemLevel? = null,
  val previousConvictions = previousConvictionsList(),
  val hasHeroinUsage: Boolean? = null,
  val hasOtherOpiateUsage: Boolean? = null,
  val hasCrackCocaineUsage: Boolean? = null,
  val hasPowderCocaineUsage: Boolean? = null,
  val hasMisusedPrescriptionDrugUsage: Boolean? = null,
  val hasBenzodiazepinesUsage: Boolean? = null,
  val hasCannabisUsage: Boolean? = null,
  val hasSteroidsUsage: Boolean? = null,
  val hasOtherDrugsUsage: Boolean? = null,
  val hasKetamineUsage: Boolean? = null,
  val hasSpiceUsage: Boolean? = null,
  val hasHallucinogensUsage: Boolean? = null,
  val hasSolventsUsage: Boolean? = null,
  val hasMethadoneUsage: Boolean? = null,
)
