package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

enum class AgeGroup {
  TEN_TO_UNDER_TWELVE,
  TWELVE_TO_UNDER_FOURTEEN,
  FOURTEEN_TO_UNDER_SIXTEEN,
  SIXTEEN_TO_UNDER_EIGHTEEN,
  EIGHTEEN_TO_UNDER_TWENTY_ONE,
  TWENTY_ONE_TO_UNDER_TWENTY_FIVE,
  TWENTY_FIVE_TO_UNDER_THIRTY,
  THIRTY_TO_UNDER_THIRTY_FIVE,
  THIRTY_FIVE_TO_UNDER_FORTY,
  FORTY_TO_UNDER_FIFTY,
  FIFTY_AND_OVER,
}
