package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.service.coefficients.SeriousViolentReoffendingPredictorDynamic
import java.math.BigDecimal

enum class PreviousConvictions(val snsvDynamicWeight: BigDecimal) {
  HOMICIDE(SeriousViolentReoffendingPredictorDynamic.PAST_HOMICIDE_OFFENCE.coefficient),
  WOUNDING_GBH(SeriousViolentReoffendingPredictorDynamic.PAST_GBH_OFFENCE.coefficient),
  KIDNAPPING(SeriousViolentReoffendingPredictorDynamic.PAST_KIDNAPPING_OFFENCE.coefficient),
  FIREARMS(SeriousViolentReoffendingPredictorDynamic.PAST_FIREARMS_OFFENCE.coefficient),
  ROBBERY(SeriousViolentReoffendingPredictorDynamic.PAST_ROBBERY_OFFENCE.coefficient),
  AGGRAVATED_BURGLARY(SeriousViolentReoffendingPredictorDynamic.PAST_AGGRAVATED_BURGLARY_OFFENCE.coefficient),
  WEAPON(SeriousViolentReoffendingPredictorDynamic.PAST_WEAPON_OFFENCE.coefficient),
  CRIMINAL_DAMAGE(SeriousViolentReoffendingPredictorDynamic.PAST_CRIMINAL_DAMAGE_OFFENCE.coefficient),
  ARSON(SeriousViolentReoffendingPredictorDynamic.PAST_ARSON_OFFENCE.coefficient),
}
