package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.lds.HasQualifications
import java.time.LocalDate

data class RiskScoreRequest(
  val version: RiskScoreVersion = RiskScoreVersion.getLatestVersion(),
  val gender: Gender? = null,
  val assessmentDate: LocalDate = LocalDate.now(),
  val dateOfBirth: LocalDate? = null,
  val dateOfCurrentConviction: LocalDate? = null,
  val dateAtStartOfFollowup: LocalDate? = null,
  val totalNumberOfSanctionsForAllOffences: Integer? = null,
  val ageAtFirstSanction: Integer? = null,
  val currentOffenceCode: String? = null,

  // OVP additional properties
  val totalNumberOfViolentSanctions: Integer? = null,
  val doesRecogniseImpactOfOffendingOnOthers: Boolean? = null,
  val isCurrentlyOfNoFixedAbodeOrTransientAccommodation: Boolean? = null,
  val isUnemployed: Boolean? = null,
  val currentAlcoholUseProblems: ProblemLevel? = null,
  val excessiveAlcoholUse: ProblemLevel? = null,
  val hasCurrentPsychiatricTreatment: Boolean? = null,
  val temperControl: ProblemLevel? = null,
  val proCriminalAttitudes: ProblemLevel? = null,

  // OGP additional properties
  val regularOffendingActivities: ProblemLevel? = null,
  val currentDrugMisuse: ProblemLevel? = null,
  val motivationToTackleDrugMisuse: MotivationLevel? = null,
  val problemSolvingSkills: ProblemLevel? = null,
  val awarenessOfConsequences: YesSometimesNo? = null,
  val understandsOtherPeoplesViews: ProblemLevel? = null,

  // MST props
  val hasPeerGroupInfluences: Boolean? = null,
  val influenceFromCriminalAssociates: ProblemLevel? = null,
  val recklessnessAndRiskTakingBehaviour: ProblemLevel? = null,
  val difficultiesCoping: ProblemLevel? = null,
  val attitudesTowardsSelf: ProblemLevel? = null,
  val impulsivityProblems: ProblemLevel? = null,

  // PNI
  val supervisionStatus: CustodyOrCommunity? = null,
  val hasEverCommittedSexualOffence: Boolean? = null,
  val isARiskOfSexualHarm: Boolean? = null,
  val sexualPreoccupation: ProblemLevel? = null,
  val offenceRelatedSexualInterests: ProblemLevel? = null,
  val emotionalCongruenceWithChildren: ProblemLevel? = null,
  val hostileOrientation: ProblemLevel? = null,
  val currentRelationshipWithFamilyMembers: ProblemLevel? = null,
  val previousCloseRelationships: ProblemLevel? = null,
  val easilyInfluencedByCriminalAssociates: ProblemLevel? = null,
  val controllingOrAggressiveBehaviour: ProblemLevel? = null,
  val saraRiskToPartner: RiskBand? = null,
  val saraRiskToOthers: RiskBand? = null,

  // OPD
  val applyOPDOverride: Boolean? = null,
  val isEligibleForMappa: Boolean? = null,
  val didOffenceInvolveCarryingOrUsingWeapon: Boolean? = null,
  val didOffenceInvolveViolenceOrThreatOfViolence: Boolean? = null,
  val didOffenceInvolveExcessiveUseOfViolence: Boolean? = null,
  val didOffenceInvolveArson: Boolean? = null,
  val offenceMotivationEmotionalState: Boolean? = null,
  val isAnalysisOfOffenceIssuesLinkedToRisk: Boolean? = null,
  val hasAccommodationIssuesLinkedToRisk: Boolean? = null,
  val experienceOfChildhood: ProblemLevel? = null,
  val evidenceOfDomesticAbuse: Boolean? = null,
  val domesticAbuseAgainstPartner: Boolean? = null,
  val domesticAbuseAgainstFamily: Boolean? = null,
  val relationshipIssuesLinkedToRisk: Boolean? = null,
  val currentPsychologicalProblems: ProblemLevel? = null,
  val areEmotionalIssuesLinkedToRisk: Boolean? = null,
  val areThinkingAndBehaviourIssuesLinkedToRisk: Boolean? = null,
  val hasCustodialSentence: Boolean? = null,
  val overRelianceOnOthersForFinancialSupport: ProblemLevel? = null,
  val manipulativeOrPredatoryBehaviour: ProblemLevel? = null,
  val isEvidenceOfChildhoodBehaviouralProblems: Boolean? = null,
  val currentPsychiatricProblems: ProblemLevel? = null,
  val hasHistoryOfPsychiatricTreatment: Boolean? = null,
  val hasBeenOnMedicationForMentalHealthProblems: Boolean? = null,
  val hasEverBeenInSpecialHospitalOrRegionalSecureUnit: Boolean? = null,
  val hasDisplayedObsessiveBehaviourLinkedToOffending: Boolean? = null,
  val hasSelfHarmOrAttemptedSuicide: Boolean? = null,
  val attitudeTowardsSupervisionOrLicence: ProblemLevel? = null,
  val hasAssaultedOrThreatenedStaff: Boolean? = null,
  val hasEscapedOrAbsconded: Boolean? = null,
  val hasControlIssues: Boolean? = null,
  val overallRiskForAssessment: RiskBand? = null,
  val highestRiskLevelOverAllAssessments: RiskBand? = null,

  // LDS
  val workRelatedSkills: ProblemLevel? = null,
  val problemsWithReadingWritingNumeracy: ProblemLevel? = null,
  val hasProblemsWithReading: Boolean? = null,
  val hasProblemsWithNumeracy: Boolean? = null,
  val learningDifficulties: ProblemLevel? = null,
  val professionalOrVocationalQualifications: HasQualifications? = null,

  // RSR
  val totalContactAdultSexualSanctions: Int? = null,
  val totalContactChildSexualSanctions: Int? = null,
  val totalIndecentImageSanctions: Int? = null,
  val totalNonContactSexualOffences: Int? = null,
  val dateOfMostRecentSexualOffence: LocalDate? = null,
  val isCurrentOffenceAgainstVictimStranger: Boolean? = null,
  val suitabilityOfAccommodation: ProblemLevel? = null,
  val currentRelationshipWithPartner: ProblemLevel? = null,
  val previousConvictions: List<PreviousConviction>? = null,
  val isCurrentOffenceSexuallyMotivated: Boolean? = null,
  val mostRecentOffenceDate: LocalDate? = null,
)
