package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.lds.HasQualifications
import java.time.LocalDate

data class RiskScoreRequest(
  val version: RiskScoreVersion = RiskScoreVersion.getLatestVersion(),
  val gender: Gender? = null,
  val assessmentDate: LocalDate = LocalDate.now(),
  val dateOfBirth: LocalDate? = null,
  val dateOfCurrentConviction: LocalDate? = null,
  val dateAtStartOfFollowup: LocalDate? = null,
  val totalNumberOfSanctions: Integer? = null,
  val ageAtFirstSanction: Integer? = null,
  val currentOffence: String? = null,

  // OVP additional properties
  val totalNumberOfViolentSanctions: Integer? = null,
  val impactOfOffendingOnOthers: Boolean? = null,
  val currentAccommodation: Boolean? = null,
  val employmentStatus: Boolean? = null,
  val alcoholIsCurrentUseAProblem: ProblemLevel? = null,
  val alcoholExcessive6Months: ProblemLevel? = null,
  val currentPsychiatricTreatmentOrPending: Boolean? = null,
  val temperControl: ProblemLevel? = null,
  val proCriminalAttitudes: ProblemLevel? = null,

  // OGP additional properties
  val regularOffendingActivities: ProblemLevel? = null,
  val currentDrugMisuse: ProblemLevel? = null,
  val motivationDrug: ProblemLevel? = null,
  val problemSolvingSkills: ProblemLevel? = null,
  val awarenessOfConsequences: ProblemLevel? = null,
  val understandsPeoplesViews: ProblemLevel? = null,

  // MST props
  val peerGroupInfluences: Boolean? = null,
  val attitudesPeerPressure: ProblemLevel? = null,
  val attitudesStableBehaviour: ProblemLevel? = null,
  val difficultiesCoping: ProblemLevel? = null,
  val attitudesTowardsSelf: ProblemLevel? = null,
  val impulsivityBehaviour: ProblemLevel? = null,

  // PNI
  val community: Boolean? = null,
  val custody: Boolean? = null,
  val hasCommittedSexualOffence: Boolean? = null,
  val riskSexualHarm: Boolean? = null,
  val sexualPreoccupation: ProblemLevel? = null,
  val sexualInterestsOffenceRelated: ProblemLevel? = null,
  val emotionalCongruence: ProblemLevel? = null,
  val hostileOrientation: ProblemLevel? = null,
  val currentRelationshipFamilyMembers: ProblemLevel? = null,
  val previousCloseRelationships: ProblemLevel? = null,
  val easilyInfluencedByCriminals: ProblemLevel? = null,
  val controllingBehaviour: ProblemLevel? = null,
  val saraRiskToPartner: RiskBand? = null,
  val saraRiskToOthers: RiskBand? = null,

  // OPD
  val opdOverride: Boolean? = null,
  val eligibleForMappa: Boolean? = null,
  val carryingOrUsingWeapon: Boolean? = null,
  val violenceOrThreatOfViolence: Boolean? = null,
  val excessiveOrSadisticViolence: Boolean? = null,
  val offenceArson: Boolean? = null,
  val offenderMotivations: Boolean? = null,
  val offenceLinkedRiskOfSeriousHarm: Boolean? = null,
  val accommodationLinkedRiskOfSeriousHarm: Boolean? = null,
  val experienceOfChildhood: ProblemLevel? = null,
  val domesticAbuse: Boolean? = null,
  val domesticAbusePartner: Boolean? = null,
  val domesticAbuseFamily: Boolean? = null,
  val relationshipLinkedSeriousHarm: Boolean? = null,
  val currentPsychologicalProblems: ProblemLevel? = null,
  val wellbeingEmotionalLinkedRiskOfSeriousHarm: Boolean? = null,
  val thinkingAndBehaviourLinedToRiskOfSeriousHarm: Boolean? = null,
  val custodialSentence: Boolean? = null,
  val financialRelianceOnOthers: ProblemLevel? = null,
  val manipulativePredatoryBehaviour: ProblemLevel? = null,
  val childhoodBehaviour: ProblemLevel? = null,
  val currentPsychiatricProblems: ProblemLevel? = null,
  val historyOfPsychiatricTreatment: Boolean? = null,
  val medicationMentalHealth: Boolean? = null,
  val patientSecureUnitOrHospital: Boolean? = null,
  val obsessiveBehaviour: Boolean? = null,
  val selfHarmSuicideAttempt: Boolean? = null,
  val concernsAboutSuicidePast: Boolean? = null,
  val concernsAboutSelfHarmPast: Boolean? = null,
  val attitudeTowardsSupervision: ProblemLevel? = null,
  val assaultedOrThreatenedStaff: Boolean? = null,
  val escapeOrAbsconded: Boolean? = null,
  val controlIssues: Boolean? = null,
  val breachOfTrust: Boolean? = null,
  val overallRiskForAssessment: RiskBand? = null,
  val highestRiskLevel: RiskBand? = null,

  // LDS
  val transferableSkills: ProblemLevel? = null,
  val educationDifficulties: ProblemLevel? = null,
  val readingDifficulties: Boolean? = null,
  val numeracyDifficulties: Boolean? = null,
  val learningDifficulties: ProblemLevel? = null,
  val professionalOrVocationalQualifications: HasQualifications? = null,
)
