package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.lds.HasQualifications
import java.time.LocalDate

data class RiskScoreRequest(
  val version: RiskScoreVersion = RiskScoreVersion.getLatestVersion(),
  val gender: Gender? = null,
  val assessmentDate: LocalDate = LocalDate.now(),
  val dateOfBirth: LocalDate? = null,
  val dateOfCurrentConviction: LocalDate? = null,
  val dateAtStartOfFollowup: LocalDate? = null,
  val totalNumberOfSanctionsForAllOffences: Integer? = null,
  val ageAtFirstSanction: Integer? = null,
  val currentOffenceCode: String? = null,

  // OVP additional properties
  val totalNumberOfViolentSanctions: Integer? = null,
  val doesRecogniseImpactOfOffendingOnOthers: Boolean? = null,
  val isCurrentlyOfNoFixedAbodeOrTransientAccommodation: Boolean? = null,
  val isUnemployed: Boolean? = null,
  val currentAlcoholUseProblems: ProblemLevel? = null,
  val excessiveAlcoholUse: ProblemLevel? = null,
  val hasCurrentPsychiatricTreatment: Boolean? = null,
  val temperControl: ProblemLevel? = null,
  val proCriminalAttitudes: ProblemLevel? = null,

  // OGP additional properties
  val regularOffendingActivities: ProblemLevel? = null,
  val currentDrugMisuse: ProblemLevel? = null,
  val motivationToTackleDrugMisuse: MotivationLevel? = null,
  val problemSolvingSkills: ProblemLevel? = null,
  val awarenessOfConsequences: YesSometimesNo? = null,
  val understandsOtherPeoplesViews: ProblemLevel? = null,

  // MST props
  val hasPeerGroupInfluences: Boolean? = null,
  val influenceFromCriminalAssociates: ProblemLevel? = null,
  val recklessnessAndRiskTakingBehaviour: ProblemLevel? = null,
  val difficultiesCoping: ProblemLevel? = null,
  val attitudesTowardsSelf: ProblemLevel? = null,
  val impulsivityProblems: ProblemLevel? = null,

  // PNI
  val supervisionStatus: CustodyOrCommunity? = null,
  val hasEverCommittedSexualOffence: Boolean? = null,
  val isARiskOfSexualHarm: Boolean? = null,
  val sexualPreoccupation: ProblemLevel? = null,
  val offenceRelatedSexualInterests: ProblemLevel? = null,
  val emotionalCongruenceWithChildren: ProblemLevel? = null,
  val hostileOrientation: ProblemLevel? = null,
  val currentRelationshipWithFamilyMembers: ProblemLevel? = null,
  val previousCloseRelationships: ProblemLevel? = null,
  val easilyInfluencedByCriminalAssociates: ProblemLevel? = null,
  val controllingOrAggressiveBehaviour: ProblemLevel? = null,
  val saraRiskToPartner: RiskBand? = null,
  val saraRiskToOthers: RiskBand? = null,

  // OPD
  val applyOPDOverride: Boolean? = null,
  val isEligibleForMappa: Boolean? = null,
  val didOffenceInvolveCarryingOrUsingWeapon: Boolean? = null,
  val didOffenceInvolveViolenceOrThreatOfViolence: Boolean? = null,
  val didOffenceInvolveExcessiveUseOfViolence: Boolean? = null,
  val didOffenceInvolveArson: Boolean? = null,
  val offenceMotivationEmotionalState: Boolean? = null,
  val offenceLinkedRiskOfSeriousHarm: Boolean? = null,
  val accommodationLinkedRiskOfSeriousHarm: Boolean? = null,
  val experienceOfChildhood: ProblemLevel? = null,
  val domesticAbuse: Boolean? = null,
  val domesticAbusePartner: Boolean? = null,
  val domesticAbuseFamily: Boolean? = null,
  val relationshipLinkedSeriousHarm: Boolean? = null,
  val currentPsychologicalProblems: ProblemLevel? = null,
  val wellbeingEmotionalLinkedRiskOfSeriousHarm: Boolean? = null,
  val thinkingAndBehaviourLinedToRiskOfSeriousHarm: Boolean? = null,
  val custodialSentence: Boolean? = null,
  val financialRelianceOnOthers: ProblemLevel? = null,
  val manipulativePredatoryBehaviour: ProblemLevel? = null,
  val childhoodBehaviour: Boolean? = null,
  val currentPsychiatricProblems: ProblemLevel? = null,
  val historyOfPsychiatricTreatment: Boolean? = null,
  val medicationMentalHealth: Boolean? = null,
  val patientSecureUnitOrHospital: Boolean? = null,
  val obsessiveBehaviour: Boolean? = null,
  val selfHarmSuicideAttempt: Boolean? = null,
  val attitudeTowardsSupervision: ProblemLevel? = null,
  val assaultedOrThreatenedStaff: Boolean? = null,
  val escapeOrAbsconded: Boolean? = null,
  val controlIssuesOrBreachOfTrust: Boolean? = null,
  val overallRiskForAssessment: RiskBand? = null,
  val highestRiskLevel: RiskBand? = null,

  // LDS
  val transferableSkills: ProblemLevel? = null,
  val educationDifficulties: ProblemLevel? = null,
  val readingDifficulties: Boolean? = null,
  val numeracyDifficulties: Boolean? = null,
  val learningDifficulties: ProblemLevel? = null,
  val professionalOrVocationalQualifications: HasQualifications? = null,

  // RSR
  val totalContactAdultSexualSanctions: Int? = null,
  val totalContactChildSexualSanctions: Int? = null,
  val totalIndecentImageSanctions: Int? = null,
  val totalNonContactSexualOffences: Int? = null,
  val dateOfMostRecentSexualOffence: LocalDate? = null,
  val victimStranger: Boolean? = null,
  val suitabilityOfAccommodation: ProblemLevel? = null,
  val currentRelationshipWithPartner: ProblemLevel? = null,
  val previousConvictions: List<PreviousConviction>? = null,
  val currentOffenceSexuallyMotivated: Boolean? = null,
  val mostRecentOffenceDate: LocalDate? = null,
)
