package uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.opd

import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.Gender
import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.ProblemLevel
import uk.gov.justice.digital.hmpps.arnsriskactuarialapi.dto.RiskBand

data class OPDRequestValidated(
  val overallRiskForAssessment: RiskBand,
  val highestRiskLevelOverAllAssessments: RiskBand,
  val gender: Gender,
  val ageAtFirstSanction: Int? = null,
  val currentOffenceCode: String,
  val applyOPDOverride: Boolean,
  val isEligibleForMappa: Boolean,
  val didOffenceInvolveCarryingOrUsingWeapon: Boolean,
  val didOffenceInvolveViolenceOrThreatOfViolence: Boolean,
  val didOffenceInvolveExcessiveUseOfViolence: Boolean,
  val didOffenceInvolveArson: Boolean,
  val offenceMotivationEmotionalState: Boolean,
  val isAnalysisOfOffenceIssuesLinkedToRisk: Boolean,
  val hasAccommodationIssuesLinkedToRisk: Boolean,
  val experienceOfChildhood: ProblemLevel? = null,
  val difficultiesCoping: ProblemLevel? = null,
  val evidenceOfDomesticAbuse: Boolean,
  val domesticAbuseAgainstPartner: Boolean?,
  val domesticAbuseAgainstFamily: Boolean?,
  val relationshipIssuesLinkedToRisk: Boolean,
  val currentPsychologicalProblems: ProblemLevel? = null,
  val hasCurrentPsychiatricTreatment: Boolean?,
  val areEmotionalIssuesLinkedToRisk: Boolean,
  val areThinkingAndBehaviourIssuesLinkedToRisk: Boolean,
  val hasCustodialSentence: Boolean,
  val overRelianceOnOthersForFinancialSupport: ProblemLevel? = null,
  val manipulativeOrPredatoryBehaviour: ProblemLevel? = null,
  val isEvidenceOfChildhoodBehaviouralProblems: Boolean,
  val currentPsychiatricProblems: ProblemLevel? = null,
  val hasBeenOnMedicationForMentalHealthProblems: Boolean,
  val hasHistoryOfPsychiatricTreatment: Boolean,
  val hasEverBeenInSpecialHospitalOrRegionalSecureUnit: Boolean,
  val hasDisplayedObsessiveBehaviourLinkedToOffending: Boolean,
  val hasSelfHarmOrAttemptedSuicide: Boolean?,
  val attitudeTowardsSupervisionOrLicence: ProblemLevel? = null,
  val controllingOrAggressiveBehaviour: ProblemLevel? = null,
  val hasAssaultedOrThreatenedStaff: Boolean?,
  val hasEscapedOrAbsconded: Boolean?,
  val hasControlIssues: Boolean?,
  val doesRecogniseImpactOfOffendingOnOthers: Boolean,
  val recklessnessAndRiskTakingBehaviour: ProblemLevel? = null,
  val impulsivityProblems: ProblemLevel? = null,
)
